<a href="https://colab.research.google.com/github/profask/ML_using_Python/blob/master/word_embedding_keras_cit_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
      ]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words']

In [ ]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4267, 1338, 1267, 7311], [4267, 1338, 1267, 7012], [4267, 4721, 1267, 9644], [9240, 7092, 8452, 8765, 3405], [9240, 7092, 8452, 8765, 7370], [1456, 4267, 1483, 1267, 9963]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
 

[[   0    0    0    0 4267 1338 1267 7311]
 [   0    0    0    0 4267 1338 1267 7012]
 [   0    0    0    0 4267 4721 1267 9644]
 [   0    0    0 9240 7092 8452 8765 3405]
 [   0    0    0 9240 7092 8452 8765 7370]
 [   0    0    0 1456 4267 1483 1267 9963]]


In [ ]:
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 2.36322619e-02 -3.97813693e-02 -1.01937652e-02 -3.28839198e-02
   -1.45313516e-02  4.98352200e-03  3.01753357e-03 -2.26056930e-02
    3.96051668e-02 -7.35331327e-04]
  [ 2.36322619e-02 -3.97813693e-02 -1.01937652e-02 -3.28839198e-02
   -1.45313516e-02  4.98352200e-03  3.01753357e-03 -2.26056930e-02
    3.96051668e-02 -7.35331327e-04]
  [ 2.36322619e-02 -3.97813693e-02 -1.01937652e-02 -3.28839198e-02
   -1.45313516e-02  4.98352200e-03  3.01753357e-03 -2.26056930e-02
    3.96051668e-02 -7.35331327e-04]
  [ 2.36322619e-02 -3.97813693e-02 -1.01937652e-02 -3.28839198e-02
   -1.45313516e-02  4.98352200e-03  3.01753357e-03 -2.26056930e-02
    3.96051668e-02 -7.35331327e-04]
  [ 4.57274355e-02  5.48856333e-03 -5.23937866e-03 -2.32342370e-02
   -1.64518505e-03 -9.71853733e-03  4.45735343e-02  3.52938809e-02
   -2.81811357e-02  7.27772713e-05]
  [-2.52672434e-02 -2.26712357e-02 -1.51939318e-03 -3.69168296e-02
   -4.21198234e-02 -4.39216867e-02 -4.53216434e-02  3.23364623e-02
    1.68577917e-

In [ ]:
embedded_docs[0]


array([   0,    0,    0,    0, 4267, 1338, 1267, 7311], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 2.3632262e-02 -3.9781369e-02 -1.0193765e-02 -3.2883920e-02
  -1.4531352e-02  4.9835220e-03  3.0175336e-03 -2.2605693e-02
   3.9605167e-02 -7.3533133e-04]
 [ 2.3632262e-02 -3.9781369e-02 -1.0193765e-02 -3.2883920e-02
  -1.4531352e-02  4.9835220e-03  3.0175336e-03 -2.2605693e-02
   3.9605167e-02 -7.3533133e-04]
 [ 2.3632262e-02 -3.9781369e-02 -1.0193765e-02 -3.2883920e-02
  -1.4531352e-02  4.9835220e-03  3.0175336e-03 -2.2605693e-02
   3.9605167e-02 -7.3533133e-04]
 [ 2.3632262e-02 -3.9781369e-02 -1.0193765e-02 -3.2883920e-02
  -1.4531352e-02  4.9835220e-03  3.0175336e-03 -2.2605693e-02
   3.9605167e-02 -7.3533133e-04]
 [ 4.5727435e-02  5.4885633e-03 -5.2393787e-03 -2.3234237e-02
  -1.6451851e-03 -9.7185373e-03  4.4573534e-02  3.5293881e-02
  -2.8181136e-02  7.2777271e-05]
 [-2.5267243e-02 -2.2671236e-02 -1.5193932e-03 -3.6916830e-02
  -4.2119823e-02 -4.3921687e-02 -4.5321643e-02  3.2336462e-02
   1.6857792e-02 -5.7895072e-03]
 [ 1.7729823e-02 -1.9851699e-03 -8.7377653e-03  3.0274097e